language: java
dist: xenial
services:
  - xvfb
addons:
  chrome: stable
  firefox: latest
cache:
  directories:
    - .autoconf
    - $HOME/.m2
env:
  - RUNWHERE=pipeline
script:
  - mvn test -Dsuite=SmokeSuite
