version: "2"
services:
  selenium-hub:
    image: selenium/hub:3.141.59-20200409
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.141.59-20200409
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444

  smoke:
    image: vinh/framework-docker
    depends_on:
      - chrome
      - firefox
    environment:
      - HUB_HOST=selenium-hub
      - SUITE="${SUITE}"
    volumes:
      - ./TestReport:/usr/share/framework/TestReport
      - ./results:/usr/share/framework/test-output
